/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wR8kvMqzCYB
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Contact() {
  return (
    <section className="bg-[#e6e7ff] py-12">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-lg sm:flex sm:items-center sm:justify-between sm:p-12">
          <div className="mb-4 sm:mb-0 sm:flex sm:flex-col">
            <h2 className="mb-2 text-2xl font-bold text-[#2C54EA]">
              Contact Us
            </h2>
          </div>
          <div className="w-full sm:flex sm:items-center">
            <Input
              className="mb-4 w-2/3 sm:mb-0 sm:mr-4"
              placeholder="Your email address..."
            />
            <Button className="bg-[#2C54EA]">Submit</Button>
          </div>
        </div>
      </div>
    </section>
  );
}
