/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eyYUSMzssjI
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export function Hero() {
  return (
    <section className="bg-[#2c54ea] text-white">
      <nav className="container mx-auto flex items-center justify-between px-4 py-6">
        <div className="flex items-center space-x-4">
          <span className="text-xl font-bold">
            <Image
              src="/assets/logo.png"
              alt="Pluto"
              width={100}
              height={100}
              layout="fixed"
            />
          </span>
        </div>
        <div className="hidden space-x-6 md:flex">
          <Link className="hover:underline" href="#">
            Home
          </Link>
          <Link className="hover:underline" href="#">
            Service
          </Link>
          <Link className="hover:underline" href="#">
            Invest
          </Link>
          <Link className="hover:underline" href="#">
            Contact
          </Link>
        </div>
        <Button className="hidden rounded-3xl bg-white text-black hover:bg-slate-300 md:block">
          Get Started
        </Button>
        <div className="md:hidden">
          <MenuIcon className="h-6 w-6" />
        </div>
      </nav>
      <div className="container mx-auto px-4 py-16 text-center">
        <h1 className="mb-6 text-5xl font-bold leading-tight">
          Pluto, Future of Startups.
        </h1>
        <p className="text-md mb-8">
          Transforming visions into achievements in our universe of
          opportunities.
        </p>
        <div className="flex justify-center space-x-4">
          <Button className="hidden rounded-3xl hover:bg-slate-800 md:block">
            Get Started
          </Button>

          <Button className="flex items-center space-x-2 rounded-3xl bg-white text-[#2c54ea] hover:bg-slate-300">
            <ChromeIcon className="h-4 w-4" />
            <span className="text-black">Sign Up with Google</span>
          </Button>
        </div>
      </div>
    </section>
  );
}

function SpaceIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  );
}
