/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/okzgckIeIND
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Navbar } from "@/components/ReusableComponents/Navbar"
import { Footer } from "@/components/ReusableComponents/Footer"

export default function Page() {
  return (
    <div>

    <Navbar/>
    <div className="min-h-screen bg-gray-100 p-4 my-10">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-4xl font-bold text-blue-800 mb-6">Our Services/Start-ups</h1>
        <div className="grid md:grid-cols-3 gap-6">
          <div className="md:col-span-2 bg-white p-6 rounded-lg shadow-md">
            <div className="flex items-center space-x-4 mb-4">
              <Avatar>
                <AvatarImage alt="Profile picture" src="/placeholder.svg?height=100&width=100" />
                <AvatarFallback>AN</AvatarFallback>
              </Avatar>
              <div className="flex flex-col">
              <p>
                <strong>Name:</strong> Alex Nguyen
              </p>
              </div>
            </div>
            <div className="space-y-2">
              <p>
                <strong>Age:</strong> 32
              </p>
              <p>
                <strong>Location:</strong> San Francisco, CA
              </p>
              <p>
                <strong>Background:</strong> Graduated with a degree in Visual Communications from a prestigious art
                school in Los Angeles.
              </p>
              <p>
                <strong>Experience:</strong> Has worked for both agencies and freelance clients, specializing in
                branding and digital design.
              </p>
              <p>
                <strong>Portfolio Highlights:</strong> Designed branding for several tech startups, including logo
                design, website development, and marketing materials.
              </p>
              <p>
                <strong>Creative Approach:</strong> Draws inspiration from urban landscapes and street art, blending
                modern aesthetics with a touch of grit.
              </p>
            </div>
            <h2 className="text-xl font-semibold mt-6 mb-4 text-blue-800">Comments:</h2>
            <div className="space-y-4">
              <div className="flex items-center justify-between bg-gray-200 p-4 rounded-lg">
                <div className="flex items-center flex-col space-y-3">
                  <div className="w-full inline-flex justify-start items-center space-x-2">
                    <Avatar>
                      <AvatarImage alt="User avatar" src="/placeholder.svg?height=40&width=40" />
                      <AvatarFallback>ST</AvatarFallback>
                    </Avatar>
                    <p className="font-semibold">Saint Tata</p>
                  </div>
                  <p className="text-sm">
                    Their portfolio showcases a diverse range of projects, from sleek tech startup branding to socially
                    conscious design initiatives. What sets Alex apart is their ability to infuse modern aesthetics with
                    a touch of raw authenticity, drawing inspiration from urban landscapes and street art. With a keen
                    eye for detail and a commitment to simplicity, Alex crafts visually compelling solutions that leave
                    a lasting impression.
                  </p>
                </div>
              </div>
            
              </div>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-md">
            <img
              alt="Profile portrait"
              className="rounded-lg mb-4"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300"
            />
            <p className="text-center">Alex Nguyen</p>
          </div>
        </div>
      </div>
    </div>
    <Footer/>
    </div>
  )
}
